import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./session-wrapper"; // Import SessionProvider wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Metadata is now allowed since "use client" is removed
export const metadata = {
  title: "DPR Gallery CMO",
  description: "Generated by create next app",
  icons: {
    icon: "/img_1.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/img_1.png" type="image/png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper> {/* ✅ Wrap children with SessionProvider */}
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
